In [2]:
import pandas as pd
import glob

csv_files = glob.glob("*.csv")

df_list = [pd.read_csv(file) for file in csv_files]
merged_df = pd.concat(df_list, ignore_index=True)
merged_df.to_csv("merged_output.csv", index=False)

print(f"Successfully merged {len(csv_files)} files!")


merged_df.head()

Successfully merged 99 files!

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:

import pandas as pd
import numpy as np


df = pd.read_csv('ecommerce_dataset.csv')


df['quantity'] = np.random.randint(1, 5, size=len(df))


print("Dataset loaded successfully!")

Dataset loaded successfully!

In [5]:
print("Dataset Shape (Rows, Columns):", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nLast 5 rows:")
display(df.tail())

Dataset Shape (Rows, Columns): (4000, 25)

Column Names:
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category', 'quantity']

Data Types:
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
quantity                    int32
dtype: object

Last 5 rows:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity
3995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890.0,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,2
3996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900.0,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,4
3997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950.0,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,2
3998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295.0,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,1
3999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699.0,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,2

In [6]:

print("Missing values BEFORE cleaning:")
print(df.isnull().sum())


df.dropna(subset=['title', 'final_price'], inplace=True)


if 'rating' in df.columns:
    median_rating = df['rating'].median()
    df['rating'] = df['rating'].fillna(median_rating)


if 'product_description' in df.columns:
    df['product_description'] = df['product_description'].fillna("No description available")


print("\nMissing values AFTER cleaning:")
print(df.isnull().sum())

Missing values BEFORE cleaning:
product_id                   0
title                        0
product_description          0
rating                       0
ratings_count                0
initial_price                0
discount                   484
final_price                  0
currency                     0
images                       0
delivery_options             0
product_details              0
breadcrumbs                  0
product_specifications       0
amount_of_stars              0
what_customers_said       2292
seller_name               1204
sizes                        0
videos                    3124
seller_information        1204
variations                2248
best_offer                   0
more_offers                  0
category                     0
quantity                     0
dtype: int64

Missing values AFTER cleaning:
product_id                   0
title                        0
product_description          0
rating                       0
ratings_count                0
initial_price                0
discount                   484
final_price                  0
currency                     0
images                       0
delivery_options             0
product_details              0
breadcrumbs                  0
product_specifications       0
amount_of_stars              0
what_customers_said       2292
seller_name               1204
sizes                        0
videos                    3124
seller_information        1204
variations                2248
best_offer                   0
more_offers                  0
category                     0
quantity                     0
dtype: int64

In [8]:
highly_rated_df = df[df['rating'] > 4.5]

print(f"Total highly rated products: {len(highly_rated_df)}")
print("Preview of highly rated products:")
display(highly_rated_df.head(3)) 

subset_df = df[['title', 'final_price', 'quantity']]

print("\n Selected Columns Subset ")
display(subset_df.head(3))

Total highly rated products: 416
Preview of highly rated products:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,2
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,2
22,21427828,London Rag,Women Stiletto Heeled High-Top Boots,5.0,4,9599.0,60.0,"""₹3,839.00""",INR,http://assets.myntassets.com/assets/images/214...,...,NaN,VOL███FAS███N P█████████,"[{""size"":""3"",""value"":""23.0cm"",""value_name"":""To...",NaN,SAI███USE███OT █████████ NA███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",boots,4

 Selected Columns Subset

            title  final_price  quantity
0     Lino Perros  "₹3,995.00"         4
1  Tommy Hilfiger  "₹2,899.00"         3
2           Lavie  "₹2,999.00"         3

In [9]:

rows_before = len(df)
print(f"Rows before removing duplicates: {rows_before}")


df.drop_duplicates(inplace=True)


rows_after = len(df)
print(f"Rows after removing duplicates: {rows_after}")
print(f"Total duplicates removed: {rows_before - rows_after}")

Rows before removing duplicates: 4000
Rows after removing duplicates: 2756
Total duplicates removed: 1244

In [11]:
df['total_amount'] = df['final_price'] * df['quantity']

print("Preview of the new 'total_amount' column:")
display(df[['title', 'final_price', 'quantity', 'total_amount']].head())

Preview of the new 'total_amount' column:

,title,final_price,quantity,total_amount
0,Lino Perros,"""₹3,995.00""",4,"""₹3,995.00""""₹3,995.00""""₹3,995.00""""₹3,995.00"""
1,Tommy Hilfiger,"""₹2,899.00""",3,"""₹2,899.00""""₹2,899.00""""₹2,899.00"""
2,Lavie,"""₹2,999.00""",3,"""₹2,999.00""""₹2,999.00""""₹2,999.00"""
3,F Gear,"""₹1,675.00""",4,"""₹1,675.00""""₹1,675.00""""₹1,675.00""""₹1,675.00"""
4,MYTRIDENT,"""₹2,899.00""",2,"""₹2,899.00""""₹2,899.00"""

In [12]:
output_filename = 'final.csv'

df.to_csv(output_filename, index=False)

print(f"Success! Your clean dataset has been saved as: {output_filename}")

Success! Your clean dataset has been saved as: final.csv